import = ["~/.config/alacritty/themes/themes/monokai_pro.toml"]

shell = "/opt/homebrew/bin/tmux"

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Full"
decorations_theme_variant = "Dark"
resize_increments = true

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 11.6

[cursor]
style = { shape = "Beam", blinking = "on" }

[terminal]
osc52 = "CopyPaste"
