[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Full"
decorations_theme_variant = "Dark"
resize_increments = true

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 11.6

[terminal]
osc52 = "CopyPaste"
