---
- name: Install k3s
  hosts: all
  become: yes
  tasks:
    - name: Allow necessary ports through UFW
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - 6443
        - 80
        - 443

    - name: Allow traffic from 10.43.0.0/16
      ufw:
        rule: allow
        from_ip: 10.43.0.0/16

    - name: Download and install k3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure k3s service is running
      service:
        name: k3s
        state: started
        enabled: yes
