"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
[](bg:green fg:black)\
$directory\
[](fg:green bg:black)\
[](fg:black bg:green)\
$git_branch\
$git_status\
[](fg:green bg:black)\
[](fg:black bg:green)\
$java\
$nodejs\
$rust\
[](fg:green bg:black)\
[](fg:black bg:green)\
$docker_context\
[ ](fg:green bg:black)\
\n$character"""

[os]
style = "bold fg:white bg:black"
disabled = false
[os.symbols]
Macos = "󰀵 "
Linux = "󰌽 "
Windows = " "

[username]
show_always = true
style_user = "bold fg:green bg:black"
style_root = "bold fg:red bg:black"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bold fg:black bg:green"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[docker_context]
symbol = " "
style = "bold fg:black bg:green"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bold fg:black bg:green"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold fg:black bg:green"
format = '[$all_status$ahead_behind ]($style)'

[java]
symbol = " "
style = "bold fg:black bg:green"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bold fg:black bg:green"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bold fg:black bg:green"
format = '[ $symbol ($version) ]($style)'
