---
- name: Setup iBox on Debian 12
  hosts: all
  become: true

  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: true
        upgrade: dist

    - name: Install necessary packages
      apt:
        name: acl
    
    - name: Ensure .ssh directory exists
      file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Remove all existing keys from authorized_keys
      lineinfile:
        path: /home/{{ ansible_user }}/.ssh/authorized_keys
        state: absent
        regexp: '.*'

    - name: Add SSH public key from host to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('pipe', 'ssh-add -L | grep vagrant_auth') }}"

    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Allow HTTP through UFW
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Allow HTTPS through UFW 
      ufw:
        rule: allow
        port: '443'
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled

- name: Import nginx playbook
  ansible.builtin.import_playbook: nginx.yml

- name: Import Hashicorp Vault playbook
  ansible.builtin.import_playbook: vault.yml

- name: Import PostgreSQL playbook
  ansible.builtin.import_playbook: postgres.yml
