---
- name: Setup iBox on Debian 12
  hosts: all
  become: yes

  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
    
    - name: Ensure .ssh directory exists
      file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Remove all existing keys from authorized_keys
      lineinfile:
        path: /home/{{ ansible_user }}/.ssh/authorized_keys
        state: absent
        regexp: '.*'

    - name: Add SSH public key from host to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('pipe', 'ssh-add -L | grep vagrant_auth') }}"

    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL is enabled and started
      systemd:
        name: postgresql
        enabled: yes
        state: started

    - name: Install ACL package
      apt:
        name: acl
        state: present

    - name: Set PostgreSQL password for the postgres user
      become_user: postgres
      shell: psql -c "ALTER USER postgres PASSWORD '{{ postgres_password }}';"

    - name: Apply PostgreSQL configuration
      copy:
        src: ./postgresql.conf
        dest: /etc/postgresql/15/main/conf.d/ibox.conf
        owner: postgres
        group: postgres
        mode: '0644'

    - name: Restart PostgreSQL to apply configuration changes
      systemd:
        name: postgresql
        state: restarted
