---
- name: Setup Vault
  hosts: all
  become: true

  tasks:
    - name: Add Hashicorp's official GPG key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Set up the Hashicorp repository
      ansible.builtin.apt_repository:
        repo: deb [arch=arm64] https://apt.releases.hashicorp.com   bookworm main
        state: present

    - name: Install Hashicorp Vault
      ansible.builtin.apt:
        name: vault
        state: present

    - name: Copy Vault systemd service file
      ansible.builtin.copy:
        src: ./resources/vault.service
        dest: /etc/systemd/system/vault.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd to recognize the new Vault service
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start Vault service
      ansible.builtin.systemd:
        name: vault
        enabled: true
        state: started
