---
- name: Install Docker via Snap
  hosts: all
  become: yes

  tasks:
    - name: Ensure snapd is installed
      apt:
        name: snapd
        state: present

    - name: Install Docker
      snap:
        name: docker
        state: present

    - name: Create docker group
      group:
        name: docker
        system: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Disable Docker snap
      command: snap disable docker

    - name: Enable Docker snap
      command: snap enable docker

    - name: Ensure .ssh directory exists
      file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Remove all existing keys from authorized_keys
      lineinfile:
        path: /home/{{ ansible_user }}/.ssh/authorized_keys
        state: absent
        regexp: '.*'

    - name: Add SSH public key from host to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('pipe', 'ssh-add -L | grep vagrant_auth') }}"
